export const metadata = { title: "Methodology & Sources — REIT/InvIT Tracker" };

export default function MethodologyPage() {
  return (
    <div className="max-w-3xl space-y-8 text-sm leading-relaxed">
      <div>
        <h1 className="text-2xl sm:text-3xl font-bold tracking-tight">Methodology &amp; sources</h1>
        <p className="text-muted-foreground mt-1">
          What each number means, where it comes from, and why we made the choices we did.
        </p>
      </div>

      <Section title="Why no live prices?">
        <p>
          Republishing real-time or delayed exchange data on a public website requires a paid
          redistribution licence from NSE Data &amp; Analytics or BSE Information Products. This is
          a zero-cost project, so we show <strong>end-of-day (EOD) prices only</strong>, refreshed
          once nightly after market close. Every price carries an &quot;as of&quot; date and a source
          note. For investing decisions, EOD data is almost always sufficient — REITs and InvITs are
          income instruments, not day-trading vehicles.
        </p>
      </Section>

      <Section title="Metrics">
        <dl className="space-y-3">
          <Dt label="TTM Yield">Sum of the last 4 quarterly distributions per unit ÷ current EOD price. Backward-looking — a falling price inflates it.</dd>
          <Dt label="Recurring Yield">TTM yield minus the return-of-capital component. Return of capital is your own money coming back, not income generated by the assets, so we separate it. Special one-off distributions are excluded when the trust labels them as such.</dd>
          <Dt label="vs NAV">(Price − NAV per unit) ÷ NAV per unit. Negative = trading below stated asset value. NAV is published half-yearly (or quarterly) by an independent valuer and is always dated — check the as-of date before reading much into it.</dd>
          <Dt label="LTV">Loan-to-value — the trust's net debt as a percentage of asset value. Lower is safer. SEBI caps apply.</dd>
          <Dt label="Occupancy (REITs)">Committed occupancy — signed leases over completed area.</dd>
          <Dt label="Concession life (InvITs)">Weighted average years remaining on toll/annuity concessions or transmission service agreements. Finite-life assets return capital as they amortise — that's why road InvITs have high return-of-capital shares.</dd>
        </dl>
      </Section>

      <Section title="Profile scorecards (published weights)">
        <p>
          We never produce a single &quot;best trust&quot; ranking, and we never compare a REIT
          against an InvIT. Instead, four profile scores (0–100) describe <em>what kind</em> of
          trust each one is:
        </p>
        <ul className="list-disc pl-5 space-y-2 mt-2">
          <li>
            <strong>Income</strong> — recurring yield (capped at 10% = 100) minus 2 points per 1%
            return-of-capital share. Formula: <code>min(recurringYield/10, 1) × 100 − rocShare% × 2</code>.
          </li>
          <li>
            <strong>Value</strong> — price vs NAV. Formula: <code>50 − navPremium% × 2.5</code>,
            clamped to 0–100. A 20% discount scores 100; a 20% premium scores 0.
          </li>
          <li>
            <strong>Safety</strong> — <code>(100 − LTV% × 1.5) × 60% + occupancy% × 40%</code>.
          </li>
          <li>
            <strong>Growth</strong> — YoY change in the last-4-quarters DPU vs the prior 4:
            <code> 50 + growthRate% × 5</code>, clamped. Needs 8 quarters of history; newer trusts
            show &quot;—&quot;.
          </li>
        </ul>
        <p className="mt-2 text-muted-foreground">
          These are descriptive heuristics, not a scoring of investment merit. The code lives in
          src/lib/metrics.ts — read it, criticise it, change it for your own use.
        </p>
      </Section>

      <Section title="Distribution component honesty">
        <p>
          Each distribution is split into interest, dividend, return of capital, and other, exactly
          as the trust declares it in its exchange filing. Where a trust has not published the split,
          the row is marked <em>unclassified</em> — we never invent a breakdown. The split matters
          because the four components are taxed differently (see the tax simulator).
        </p>
      </Section>

      <Section title="Tax rules used (resident individual, FY2026-27)">
        <ul className="list-disc pl-5 space-y-1.5">
          <li>Interest component: taxed at slab rate; TDS 10% u/s 194LBA.</li>
          <li>Dividend component: exempt where the underlying SPVs opted the concessional corporate tax regime, otherwise slab rate. We store a per-trust flag; where unknown we show both.</li>
          <li>Return of capital: not current income — reduces cost basis. Cumulative amounts above the original issue price become taxable as income (the &quot;specified sum&quot; rule).</li>
          <li>STCG (held ≤ 12 months, STT paid): 20% u/s 111A.</li>
          <li>LTCG (held &gt; 12 months): 12.5% u/s 112A with the ₹1.25 lakh annual exemption.</li>
        </ul>
        <p className="mt-2 text-muted-foreground">
          Tax law changes. This site is education, not advice — consult a chartered accountant.
        </p>
      </Section>

      <Section title="Data sources & refresh">
        <ul className="list-disc pl-5 space-y-1.5">
          <li>Prices: BSE India public API, refreshed nightly (~17:30 IST) by a GitHub Action.</li>
          <li>Distributions, NAV, LTV, occupancy: official trust investor-relations pages and BSE/NSE exchange filings. Each figure carries an as-of date and a source link on the trust page.</li>
          <li>Identifiers (ISIN ↔ symbol): Upstox public instrument dump.</li>
        </ul>
        <p className="mt-2">
          If the nightly refresh fails (e.g. an expired API token), the site keeps serving the last
          good data and the failure is visible in the repo's Actions log — stale data is always
          labelled by its as-of date.
        </p>
      </Section>

      <Section title="What this site deliberately does not do">
        <ul className="list-disc pl-5 space-y-1.5">
          <li>No live or intraday prices (licensing — see above).</li>
          <li>No single ranking of trusts across types.</li>
          <li>No forecasts presented as fact. Bear/base/bull in the calculator is a sensitivity tool, not a prediction.</li>
          <li>No accounts, no tracking of your portfolio off-device.</li>
          <li>Privately placed InvITs (25,000-unit lots) and SM REITs are excluded — they are not retail products.</li>
        </ul>
      </Section>

      <div className="rounded-lg border border-border bg-muted/40 p-4 text-xs text-muted-foreground">
        This site is not registered with SEBI as an investment adviser or research analyst. Nothing
        here is investment advice or a recommendation. Verify all figures against official trust
        disclosures before acting.
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-2">
      <h2 className="text-lg font-semibold">{title}</h2>
      <div className="text-muted-foreground space-y-2">{children}</div>
    </section>
  );
}

function Dt({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <dt className="font-medium text-foreground">{label}</dt>
      <dd className="text-muted-foreground">{children}</dd>
    </div>
  );
}
